//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciendo.Music.DataProviders.MusicClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Sciendo.Indexer.Agent", ConfigurationName="MusicClient.IMusic")]
    public interface IMusic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/IndexLyricsOnDemand", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/IndexLyricsOnDemandResponse")]
        int IndexLyricsOnDemand(string fromPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/IndexLyricsOnDemand", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/IndexLyricsOnDemandResponse")]
        System.Threading.Tasks.Task<int> IndexLyricsOnDemandAsync(string fromPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/IndexMusicOnDemand", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/IndexMusicOnDemandResponse")]
        int IndexMusicOnDemand(string fromPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/IndexMusicOnDemand", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/IndexMusicOnDemandResponse")]
        System.Threading.Tasks.Task<int> IndexMusicOnDemandAsync(string fromPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/AcquireLyricsFor", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/AcquireLyricsForResponse")]
        int AcquireLyricsFor(string musicPath, bool retryFailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/AcquireLyricsFor", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/AcquireLyricsForResponse")]
        System.Threading.Tasks.Task<int> AcquireLyricsForAsync(string musicPath, bool retryFailed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/GetLastProcessedPackages", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/GetLastProcessedPackagesResponse")]
        Sciendo.Music.Contracts.MusicService.ProgressStatus[] GetLastProcessedPackages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/GetLastProcessedPackages", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/GetLastProcessedPackagesResponse")]
        System.Threading.Tasks.Task<Sciendo.Music.Contracts.MusicService.ProgressStatus[]> GetLastProcessedPackagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/ListAvailableMusicPathsForIndexing", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/ListAvailableMusicPathsForIndexingResponse")]
        string[] ListAvailableMusicPathsForIndexing(string fromPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/ListAvailableMusicPathsForIndexing", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/ListAvailableMusicPathsForIndexingResponse")]
        System.Threading.Tasks.Task<string[]> ListAvailableMusicPathsForIndexingAsync(string fromPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/ListAvailableLyricsPathsForIndexing", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/ListAvailableLyricsPathsForIndexingResponse")]
        string[] ListAvailableLyricsPathsForIndexing(string fromPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/ListAvailableLyricsPathsForIndexing", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/ListAvailableLyricsPathsForIndexingResponse")]
        System.Threading.Tasks.Task<string[]> ListAvailableLyricsPathsForIndexingAsync(string fromPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/GetSourceFolders", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/GetSourceFoldersResponse")]
        Sciendo.Music.Contracts.MusicService.SourceFolders GetSourceFolders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IMusic/GetSourceFolders", ReplyAction="http://Sciendo.Indexer.Agent/IMusic/GetSourceFoldersResponse")]
        System.Threading.Tasks.Task<Sciendo.Music.Contracts.MusicService.SourceFolders> GetSourceFoldersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMusicChannel : Sciendo.Music.DataProviders.MusicClient.IMusic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusicClient : System.ServiceModel.ClientBase<Sciendo.Music.DataProviders.MusicClient.IMusic>, Sciendo.Music.DataProviders.MusicClient.IMusic {
        
        public MusicClient() {
        }
        
        public MusicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int IndexLyricsOnDemand(string fromPath) {
            return base.Channel.IndexLyricsOnDemand(fromPath);
        }
        
        public System.Threading.Tasks.Task<int> IndexLyricsOnDemandAsync(string fromPath) {
            return base.Channel.IndexLyricsOnDemandAsync(fromPath);
        }
        
        public int IndexMusicOnDemand(string fromPath) {
            return base.Channel.IndexMusicOnDemand(fromPath);
        }
        
        public System.Threading.Tasks.Task<int> IndexMusicOnDemandAsync(string fromPath) {
            return base.Channel.IndexMusicOnDemandAsync(fromPath);
        }
        
        public int AcquireLyricsFor(string musicPath, bool retryFailed) {
            return base.Channel.AcquireLyricsFor(musicPath, retryFailed);
        }
        
        public System.Threading.Tasks.Task<int> AcquireLyricsForAsync(string musicPath, bool retryFailed) {
            return base.Channel.AcquireLyricsForAsync(musicPath, retryFailed);
        }
        
        public Sciendo.Music.Contracts.MusicService.ProgressStatus[] GetLastProcessedPackages() {
            return base.Channel.GetLastProcessedPackages();
        }
        
        public System.Threading.Tasks.Task<Sciendo.Music.Contracts.MusicService.ProgressStatus[]> GetLastProcessedPackagesAsync() {
            return base.Channel.GetLastProcessedPackagesAsync();
        }
        
        public string[] ListAvailableMusicPathsForIndexing(string fromPath) {
            return base.Channel.ListAvailableMusicPathsForIndexing(fromPath);
        }
        
        public System.Threading.Tasks.Task<string[]> ListAvailableMusicPathsForIndexingAsync(string fromPath) {
            return base.Channel.ListAvailableMusicPathsForIndexingAsync(fromPath);
        }
        
        public string[] ListAvailableLyricsPathsForIndexing(string fromPath) {
            return base.Channel.ListAvailableLyricsPathsForIndexing(fromPath);
        }
        
        public System.Threading.Tasks.Task<string[]> ListAvailableLyricsPathsForIndexingAsync(string fromPath) {
            return base.Channel.ListAvailableLyricsPathsForIndexingAsync(fromPath);
        }
        
        public Sciendo.Music.Contracts.MusicService.SourceFolders GetSourceFolders() {
            return base.Channel.GetSourceFolders();
        }
        
        public System.Threading.Tasks.Task<Sciendo.Music.Contracts.MusicService.SourceFolders> GetSourceFoldersAsync() {
            return base.Channel.GetSourceFoldersAsync();
        }
    }
}
