//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciendo.Indexer.Client {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgressStatus", Namespace="http://schemas.datacontract.org/2004/07/Sciendo.Indexer.Agent.Service")]
    [System.SerializableAttribute()]
    public partial class ProgressStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sciendo.Indexer.Client.Status StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Package {
            get {
                return this.PackageField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageField, value) != true)) {
                    this.PackageField = value;
                    this.RaisePropertyChanged("Package");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sciendo.Indexer.Client.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/Sciendo.Lyrics.Common")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotStarted = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileNotTagged = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownTagVersion = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArtistSongRetrievedFromFile = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LyricsUrlUnreachable = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LyricsDownloadedOk = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotIndexed = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Done = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Sciendo.Indexer.Agent", ConfigurationName="Client.IIndexerAgent")]
    public interface IIndexerAgent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IIndexerAgent/IndexLyricsOnDemand", ReplyAction="http://Sciendo.Indexer.Agent/IIndexerAgent/IndexLyricsOnDemandResponse")]
        Sciendo.Indexer.Client.IndexLyricsOnDemandResponse IndexLyricsOnDemand(Sciendo.Indexer.Client.IndexLyricsOnDemandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IIndexerAgent/IndexMusicOnDemand", ReplyAction="http://Sciendo.Indexer.Agent/IIndexerAgent/IndexMusicOnDemandResponse")]
        Sciendo.Indexer.Client.IndexMusicOnDemandResponse IndexMusicOnDemand(Sciendo.Indexer.Client.IndexMusicOnDemandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IIndexerAgent/GetLastProcessedPackages", ReplyAction="http://Sciendo.Indexer.Agent/IIndexerAgent/GetLastProcessedPackagesResponse")]
        Sciendo.Indexer.Client.GetLastProcessedPackagesResponse GetLastProcessedPackages(Sciendo.Indexer.Client.GetLastProcessedPackagesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IndexLyricsOnDemand", WrapperNamespace="http://Sciendo.Indexer.Agent", IsWrapped=true)]
    public partial class IndexLyricsOnDemandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Sciendo.Indexer.Agent", Order=0)]
        public string fromPath;
        
        public IndexLyricsOnDemandRequest() {
        }
        
        public IndexLyricsOnDemandRequest(string fromPath) {
            this.fromPath = fromPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IndexLyricsOnDemandResponse", WrapperNamespace="http://Sciendo.Indexer.Agent", IsWrapped=true)]
    public partial class IndexLyricsOnDemandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Sciendo.Indexer.Agent", Order=0)]
        public int IndexLyricsOnDemandResult;
        
        public IndexLyricsOnDemandResponse() {
        }
        
        public IndexLyricsOnDemandResponse(int IndexLyricsOnDemandResult) {
            this.IndexLyricsOnDemandResult = IndexLyricsOnDemandResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IndexMusicOnDemand", WrapperNamespace="http://Sciendo.Indexer.Agent", IsWrapped=true)]
    public partial class IndexMusicOnDemandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Sciendo.Indexer.Agent", Order=0)]
        public string fromPath;
        
        public IndexMusicOnDemandRequest() {
        }
        
        public IndexMusicOnDemandRequest(string fromPath) {
            this.fromPath = fromPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IndexMusicOnDemandResponse", WrapperNamespace="http://Sciendo.Indexer.Agent", IsWrapped=true)]
    public partial class IndexMusicOnDemandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Sciendo.Indexer.Agent", Order=0)]
        public int IndexMusicOnDemandResult;
        
        public IndexMusicOnDemandResponse() {
        }
        
        public IndexMusicOnDemandResponse(int IndexMusicOnDemandResult) {
            this.IndexMusicOnDemandResult = IndexMusicOnDemandResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastProcessedPackages", WrapperNamespace="http://Sciendo.Indexer.Agent", IsWrapped=true)]
    public partial class GetLastProcessedPackagesRequest {
        
        public GetLastProcessedPackagesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastProcessedPackagesResponse", WrapperNamespace="http://Sciendo.Indexer.Agent", IsWrapped=true)]
    public partial class GetLastProcessedPackagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Sciendo.Indexer.Agent", Order=0)]
        public Sciendo.Indexer.Client.ProgressStatus[] GetLastProcessedPackagesResult;
        
        public GetLastProcessedPackagesResponse() {
        }
        
        public GetLastProcessedPackagesResponse(Sciendo.Indexer.Client.ProgressStatus[] GetLastProcessedPackagesResult) {
            this.GetLastProcessedPackagesResult = GetLastProcessedPackagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIndexerAgentChannel : Sciendo.Indexer.Client.IIndexerAgent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndexerAgentClient : System.ServiceModel.ClientBase<Sciendo.Indexer.Client.IIndexerAgent>, Sciendo.Indexer.Client.IIndexerAgent {
        
        public IndexerAgentClient() {
        }
        
        public IndexerAgentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndexerAgentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexerAgentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexerAgentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sciendo.Indexer.Client.IndexLyricsOnDemandResponse IndexLyricsOnDemand(Sciendo.Indexer.Client.IndexLyricsOnDemandRequest request) {
            return base.Channel.IndexLyricsOnDemand(request);
        }
        
        public Sciendo.Indexer.Client.IndexMusicOnDemandResponse IndexMusicOnDemand(Sciendo.Indexer.Client.IndexMusicOnDemandRequest request) {
            return base.Channel.IndexMusicOnDemand(request);
        }
        
        public Sciendo.Indexer.Client.GetLastProcessedPackagesResponse GetLastProcessedPackages(Sciendo.Indexer.Client.GetLastProcessedPackagesRequest request) {
            return base.Channel.GetLastProcessedPackages(request);
        }
    }
}
