//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sciendo.Indexer.Client {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Sciendo.Indexer.Agent", ConfigurationName="Client.IIndexerAgent")]
    public interface IIndexerAgent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IIndexerAgent/IndexLyricsOnDemand", ReplyAction="http://Sciendo.Indexer.Agent/IIndexerAgent/IndexLyricsOnDemandResponse")]
        Sciendo.Indexer.Client.IndexLyricsOnDemandResponse IndexLyricsOnDemand(Sciendo.Indexer.Client.IndexLyricsOnDemandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sciendo.Indexer.Agent/IIndexerAgent/IndexMusicOnDemand", ReplyAction="http://Sciendo.Indexer.Agent/IIndexerAgent/IndexMusicOnDemandResponse")]
        Sciendo.Indexer.Client.IndexMusicOnDemandResponse IndexMusicOnDemand(Sciendo.Indexer.Client.IndexMusicOnDemandRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IndexLyricsOnDemand", WrapperNamespace="http://Sciendo.Indexer.Agent", IsWrapped=true)]
    public partial class IndexLyricsOnDemandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Sciendo.Indexer.Agent", Order=0)]
        public string fromPath;
        
        public IndexLyricsOnDemandRequest() {
        }
        
        public IndexLyricsOnDemandRequest(string fromPath) {
            this.fromPath = fromPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IndexLyricsOnDemandResponse", WrapperNamespace="http://Sciendo.Indexer.Agent", IsWrapped=true)]
    public partial class IndexLyricsOnDemandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Sciendo.Indexer.Agent", Order=0)]
        public int IndexLyricsOnDemandResult;
        
        public IndexLyricsOnDemandResponse() {
        }
        
        public IndexLyricsOnDemandResponse(int IndexLyricsOnDemandResult) {
            this.IndexLyricsOnDemandResult = IndexLyricsOnDemandResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IndexMusicOnDemand", WrapperNamespace="http://Sciendo.Indexer.Agent", IsWrapped=true)]
    public partial class IndexMusicOnDemandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Sciendo.Indexer.Agent", Order=0)]
        public string fromPath;
        
        public IndexMusicOnDemandRequest() {
        }
        
        public IndexMusicOnDemandRequest(string fromPath) {
            this.fromPath = fromPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IndexMusicOnDemandResponse", WrapperNamespace="http://Sciendo.Indexer.Agent", IsWrapped=true)]
    public partial class IndexMusicOnDemandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Sciendo.Indexer.Agent", Order=0)]
        public int IndexMusicOnDemandResult;
        
        public IndexMusicOnDemandResponse() {
        }
        
        public IndexMusicOnDemandResponse(int IndexMusicOnDemandResult) {
            this.IndexMusicOnDemandResult = IndexMusicOnDemandResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIndexerAgentChannel : Sciendo.Indexer.Client.IIndexerAgent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndexerAgentClient : System.ServiceModel.ClientBase<Sciendo.Indexer.Client.IIndexerAgent>, Sciendo.Indexer.Client.IIndexerAgent {
        
        public IndexerAgentClient() {
        }
        
        public IndexerAgentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndexerAgentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexerAgentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndexerAgentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sciendo.Indexer.Client.IndexLyricsOnDemandResponse IndexLyricsOnDemand(Sciendo.Indexer.Client.IndexLyricsOnDemandRequest request) {
            return base.Channel.IndexLyricsOnDemand(request);
        }
        
        public Sciendo.Indexer.Client.IndexMusicOnDemandResponse IndexMusicOnDemand(Sciendo.Indexer.Client.IndexMusicOnDemandRequest request) {
            return base.Channel.IndexMusicOnDemand(request);
        }
    }
}
